# Generated by Django 4.2.21 on 2025-06-07 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music_h_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('expression', models.CharField(choices=[('neutral', 'Neutral'), ('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('fearful', 'Fearful'), ('disgusted', 'Disgusted'), ('surprised', 'Surprised')], max_length=20)),
                ('confidence', models.FloatField()),
                ('neutral', models.FloatField()),
                ('happy', models.FloatField()),
                ('sad', models.FloatField()),
                ('angry', models.FloatField()),
                ('fearful', models.FloatField()),
                ('disgusted', models.FloatField()),
                ('surprised', models.FloatField()),
                ('image', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
