# Generated by Django 4.2.21 on 2025-06-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_h_app', '0002_expressionrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expressionrecord',
            name='image',
        ),
    ]
